export default y = {
  "adult":"a*d*l*",
  "akouka":"a*o*k*",
  "alkohol":"a*l*o*o*",
  "anak haram":"a*a* *a*a*",
  "anak yatim":"a*a* *a*i*",
  "analex":"a*a*e*",
  "anjing":"a*j*n*",
  "anjink":"a*j*n*",
  "anjir":"a*n*i*",
  "arsundal":"a*s*n*a*",
  "asu":"a*u",
  "autis":"a*u*i*",
  "azizay":"a*i*a*",
  "babi":"b*bi",
  "babi lu":"b*a*i*l*",
  "bacot":"b*a*o*",
  "bajingan":"b*j*n*a*",
  "bajingan tengik":"b*a*i*g*n*t*n*ik",
  "bakka":"b*a*k*",
  "banci":"b*a*c*",
  "bandar":"b*n*a*",
  "bangke":"b*n*k*",
  "bangsat":"b*a*g*a*",
  "bawel":"b*a*e*",
  "bebon":"b*e*o*",
  "bedebah":"b*e*e*a*",
  "bedon":"b*e*o*",
  "beer":"b*er",
  "bego":"b*go",
  "begok":"b*e*o*",
  "bencong":"b*e*c*n*",
  "berak":"b*e*a*",
  "bercinta":"b*r*i*t*",
  "berengsek":"b*e*e*g*e*",
  "bersetubuh":"b*r*e*u*u*",
  "bestiality":"b*s*i*l*t*",
  "betting":"b*e*t*n*",
  "biadab":"b*a*a*",
  "bispak":"b*s*a*",
  "bitch":"b*i*c*",
  "blo'on":"b*o*o*",
  "blowjob":"b*l*w*o*",
  "bo’ol":"b*o*o*",
  "bodo":"b*do",
  "bodoh":"b*o*o*",
  "bodooohhh":"b*o*o*o*h*",
  "bokep":"b*o*e*",
  "boker":"b*o*e*",
  "bokong":"b*k*n*",
  "borok":"b*o*o*",
  "bot":"b*t",
  "breast":"b*e*s*",
  "brengsek":"b*e*g*e*",
  "brengsex":"b*e*g*e*",
  "brengsexxx":"b*e*g*e*x*",
  "buah dada":"b*u*h*d*d*",
  "buah zakar":"b*a* *a*a*",
  "buaya":"b*u*y*",
  "buaya darat":"b*u*y* *a*a*",
  "budeg":"b*u*e*",
  "bugil":"b*u*i*",
  "bujang inam":"b*u*a*g*i*a*",
  "Burung":"B*r*n*",
  "cabe lo":"c*a*e*l*",
  "cabo":"c*bo",
  "cacat":"c*a*a*",
  "cacat lu":"c*c*t*l*",
  "cangcut":"c*a*g*u*",
  "caper":"c*a*e*",
  "ccookkk":"c*c*o*k*",
  "cebong":"c*b*n*",
  "celaka":"c*l*k*",
  "celeng":"c*l*n*",
  "celsit":"c*l*i*",
  "centil":"c*n*i*",
  "chealeng":"c*e*l*n*",
  "chealshit":"c*h*a*s*i*",
  "cheleng":"c*h*l*n*",
  "cheleng tikus":"c*h*l*n* *i*u*",
  "chellenk":"c*e*l*n*",
  "chelshit":"c*e*s*i*",
  "chleng":"c*l*n*",
  "cilaka":"c*l*k*",
  "cina":"c*na",
  "citikus":"c*i*i*u*",
  "citykus":"c*i*y*u*",
  "cium pantat ku":"c*u* *a*t*t*k*",
  "cock":"c*ck",
  "coitus":"c*i*u*",
  "congek":"c*n*e*",
  "cumi":"c*mi",
  "curut":"c*u*u*",
  "dafuq":"d*a*u*",
  "dajal":"d*a*a*",
  "davit monyet":"d*v*t*m*n*e*",
  "dekil":"d*e*i*",
  "dengkulmu":"d*e*g*u*m*",
  "detik":"d*e*i*",
  "dodol":"d*o*o*",
  "dongok":"d*n*o*",
  "downline":"d*w*l*n*",
  "drug":"d*ug",
  "drunken":"d*r*n*e*",
  "dungu":"d*u*g*",
  "ectasy":"e*t*s*",
  "edan":"e*an",
  "eek":"e*k",
  "ejakulasi":"e*j*k*l*s*",
  "eneg":"e*eg",
  "enti":"e*ti",
  "erotic":"e*o*i*",
  "erotis":"e*o*i*",
  "ewe":"e*e",
  "fak":"fucek",
  "fakk":"fucekk",
  "fergay":"f*r*a*",
  "fetish":"f*t*s*",
  "foto hot":"f*t* *o*",
  "foto panas":"f*t* *a*a*",
  "fuck":"fceek",
  "fuck you":"fuceek fucek",
  "galau-galau munyuk":"g*l*u*g*l*u*m*nyuk",
  "ganjen":"g*n*e*",
  "ganyang":"g*a*y*n*",
  "gay":"g*y",
  "geblek":"g*b*e*",
  "gelandangan":"g*e*a*d*n*a*",
  "gelo":"g*lo",
  "gembel":"g*m*e*",
  "gigolo":"g*g*l*",
  "gila":"g*la",
  "goblog":"g*b*o*",
  "goblok":"g*b*o*",
  "goblokk":"g*o*l*k*",
  "gobloookkkkk":"g*b*o*o*k*k*",
  "grogol grogol":"g*r*g*l*g*o*o*",
  "grogol grogol munyak":"g*o*o* *r*g*l*munyak",
  "guk-guk mu":"g*k*g*k*m*",
  "handjob":"h*a*d*o*",
  "haram jadah":"h*a*a* *a*a*",
  "heunceut":"h*u*c*u*",
  "homo":"h*mo",
  "homoseksual":"h*o*o*e*s*a*",
  "hot girl":"h*t*g*r*",
  "hot model":"h*o* *o*e*",
  "hot picture":"h*o* *i*t*r*",
  "hot video":"h*o* *i*e*",
  "hubungan intim":"h*b*n*a* *n*i*",
  "iblis":"i*b*i*",
  "idiot":"i*d*o*",
  "inex":"i*ex",
  "intercouse":"i*t*r*o*s*",
  "intim":"i*n*i*",
  "itil":"i*il",
  "jablay":"j*b*a*",
  "jahanam":"j*a*a*a*",
  "jalang":"j*l*n*",
  "jam8an":"j*m*a*",
  "jamban":"j*m*a*",
  "jancok":"j*n*o*",
  "Jancuk":"J*n*u*",
  "Jangkrik":"J*n*k*i*",
  "jaran":"j*a*a*",
  "Jayus":"J*a*u*",
  "Jayus lo":"J*y*s*l*",
  "jeber bau tai":"j*e*e* *a* *a*",
  "jelek lu":"j*l*k*l*",
  "jembel":"j*m*e*",
  "jembut":"j*m*u*",
  "jiancux":"j*i*n*u*",
  "jijik gua**":"j*i*i* *u***",
  "judi":"j*di",
  "kadal":"k*a*a*",
  "kafir":"k*a*i*",
  "kalempong":"k*a*e*p*n*",
  "kamasutra":"k*a*a*u*r*",
  "kambing":"k*a*b*n*",
  "kampret":"k*a*p*e*",
  "kampungan":"k*a*p*n*a*",
  "kancut":"k*n*u*",
  "kanjut":"k*n*u*",
  "kaparat":"k*a*a*a*",
  "katrok":"k*t*o*",
  "kecepirit":"k*e*e*i*i*",
  "keledai":"k*e*e*a*",
  "kentut":"k*n*u*",
  "keparat":"k*e*a*a*",
  "keperawanan":"k*e*e*a*a*a*",
  "kere":"k*re",
  "klik":"k*ik",
  "kolor":"k*o*o*",
  "kondom":"k*n*o*",
  "kontol":"k*n*o*",
  "kontol babi":"k*o*t*l*b*b*",
  "kontol mamakmu":"k*n*o* *a*a*m*",
  "kunyuk":"k*n*u*",
  "labia":"l*a*i*",
  "laknat":"l*k*a*",
  "leak":"l*ak",
  "lebay":"l*e*a*",
  "lebok":"l*e*o*",
  "lesbian":"l*e*b*a*",
  "live sex":"l*v* *e*",
  "lonte":"l*o*t*",
  "loserfool":"l*o*e*f*o*",
  "maaampooos":"m*a*m*o*o*",
  "mabuk":"m*a*u*",
  "madura":"m*d*r*",
  "maho":"m*ho",
  "makan tai":"m*a*a* *a*",
  "make love":"m*a*e*l*v*",
  "maling":"m*l*n*",
  "mamakmu berkontol":"m*a*a*m* *e*k*ntol",
  "mampoooos":"m*a*p*o*o*",
  "mampos":"m*m*o*",
  "mampus":"m*m*u*",
  "mampuz":"m*m*u*",
  "manasturbo":"m*n*s*u*b*",
  "mandul":"m*n*u*",
  "martole":"m*a*t*l*",
  "masturbasi":"m*s*u*b*s*",
  "masturbate":"m*s*u*b*t*",
  "matamu":"m*t*m*",
  "mati":"m*ti",
  "meki":"m*ki",
  "memek":"m*e*e*",
  "memek busuk":"m*e*e* *u*u*",
  "memex":"m*e*e*",
  "mesum":"m*e*u*",
  "miyabi":"m*y*b*",
  "modar":"m*o*a*",
  "moddar":"m*d*a*",
  "monyet":"m*n*e*",
  "monyong":"m*o*y*n*",
  "mother fucker":"m*o*h*r*f*c*e*",
  "muka boros":"m*k* *o*o*",
  "muka plastik":"m*k* *l*s*i*",
  "muka sange":"m*k* *a*g*",
  "munyuk":"m*n*u*",
  "munyukers":"m*u*y*k*r*",
  "munyuuk":"m*u*y*u*",
  "murahan":"m*u*a*a*",
  "najis lu":"n*j*s*l*",
  "najong":"n*j*n*",
  "naked":"n*a*e*",
  "narkoba":"n*a*k*b*",
  "narkotika":"n*a*k*t*k*",
  "nekrofilia":"n*k*o*i*i*",
  "ngaceng":"n*g*c*n*",
  "ngenti":"n*e*t*",
  "ngentot":"n*g*n*o*",
  "ngepet":"n*e*e*",
  "ngeseks":"n*g*s*k*",
  "ngewe":"n*g*w*",
  "ngocok":"n*o*o*",
  "njing":"n*j*n*",
  "nono":"n*no",
  "nonok":"n*o*o*",
  "norak":"n*o*a*",
  "nude":"n*de",
  "nyemot":"n*e*o*",
  "nyolot":"n*o*o*",
  "nyuk":"n*uk",
  "onani":"o*n*n*",
  "onta":"o*ta",
  "oral sex":"o*a* *e*",
  "orang kampung":"o*r*n* *a*p*n*",
  "orang udik":"o*a*g*u*i*",
  "orgasm":"o*g*s*",
  "orgasme":"o*r*a*m*",
  "otak melayu":"o*t*k*m*l*y*",
  "otak miring":"o*t*k*m*r*n*",
  "otak udang":"o*a* *d*n*",
  "otakmu":"o*a*m*",
  "ozawa":"o*z*w*",
  "paedofilia":"p*e*o*i*i*",
  "palaji":"p*l*j*",
  "palkon":"p*l*o*",
  "pantat":"p*n*a*",
  "pantek":"p*n*e*",
  "parafilia":"p*a*a*i*i*",
  "payudara":"p*y*d*r*",
  "pe’a":"p*’a",
  "pecun":"p*e*u*",
  "peju":"p*ju",
  "pelacur":"p*e*a*u*",
  "pelakor":"p*e*a*o*",
  "pele":"p*le",
  "peler":"p*e*e*",
  "pemerkosa":"p*e*e*k*s*",
  "pengemis":"p*n*e*i*",
  "penis":"p*e*i*",
  "pepet":"p*e*e*",
  "perawan":"p*e*a*a*",
  "perek":"p*e*e*",
  "perkosa":"p*e*k*s*",
  "playboy":"p*l*y*o*",
  "porn":"p*rn",
  "porno":"p*o*n*",
  "pukimai":"p*u*i*a*",
  "pukimak":"p*u*i*a*",
  "pulsa":"p*u*s*",
  "pussy":"p*u*s*",
  "rape":"r*pe",
  "raping":"r*p*n*",
  "robot":"r*o*o*",
  "sakit jiwa":"s*k*t*j*w*",
  "sampah":"s*m*a*",
  "sarap":"s*a*a*",
  "seks":"s*ks",
  "selangkangan":"s*l*n*k*n*a*",
  "self service":"s*l* *e*v*c*",
  "sempak":"s*m*a*",
  "sendal":"s*n*a*",
  "senggama":"s*n*g*m*",
  "setan":"s*e*a*",
  "settubuh":"s*t*u*u*",
  "sex":"s*x",
  "sex toy":"s*e* *o*",
  "sexual":"s*x*a*",
  "shit":"s*it",
  "sial":"s*al",
  "sialan":"s*a*a*",
  "sialan lu":"s*i*l*n*l*",
  "silit":"s*i*i*",
  "sinting":"s*i*t*n*",
  "sperma":"s*e*m*",
  "sundal":"s*n*a*",
  "taek":"t*ek",
  "taex":"t*ex",
  "tahi":"t*hi",
  "tahi kucing":"t*a*i*k*c*n*",
  "tai":"t*i",
  "Tai lo":"T*i*l*",
  "taik":"t*ik",
  "tampang tua":"t*a*p*n* *u*",
  "tampol":"t*m*o*",
  "telanjang":"t*e*a*j*n*",
  "testicles":"t*e*t*c*e*",
  "testis":"t*s*i*",
  "tetek":"t*e*e*",
  "titit":"t*i*i*",
  "tokai":"t*o*a*",
  "tokek belang":"t*k*k*b*l*n*",
  "toket":"t*o*e*",
  "tolo":"t*lo",
  "tolol":"t*o*o*",
  "topless":"t*o*l*s*",
  "tukang bohong":"t*u*a*g*b*h*n*",
  "ublag":"u*b*a*",
  "udik":"u*ik",
  "united":"u*i*e*",
  "vagina":"v*g*n*",
  "video hot":"v*i*e* *o*",
  "video panas":"v*i*e* *a*a*",
  "virginity":"v*i*g*n*t*",
  "vodka":"v*o*k*",
  "vulva":"v*u*v*",
  "xxx":"x*x",
  "zakar":"z*a*a*",
  "zakar kecil":"z*a*a* *e*i*",
  "zoofilia":"z*o*i*i*",
  "2 girls 1 cup":"2* *i*l* * *u*",
  "2g1c":"2*1c",
  "4r5e":"4*5e",
  "5h1t":"5*1t",
  "5hit":"5*it",
  "a$$":"a*$",
  "a$$hole":"a*$*h*l*",
  "a_s_s":"a*_*_*",
  "a2m":"a*m",
  "a54":"a*4",
  "a55":"a*5",
  "a55hole":"a*5*h*l*",
  "acrotomophilia":"a*r*t*m*p*i*i*",
  "aeolus":"a*o*u*",
  "ahole":"a*h*l*",
  "alabama hot pocket":"a*a*a*a*h*t*p*cket",
  "alaskan pipeline":"a*a*k*n*p*p*l*ne",
  "anal":"a*al",
  "anal impaler":"a*a* *m*a*e*",
  "anal leakage":"a*a* *e*k*g*",
  "analprobe":"a*n*l*r*b*",
  "anilingus":"a*n*l*n*u*",
  "anus":"a*us",
  "apeshit":"a*p*s*i*",
  "ar5e":"a*5e",
  "areola":"a*e*l*",
  "areole":"a*e*l*",
  "arian":"a*r*a*",
  "arrse":"a*r*s*",
  "arse":"a*se",
  "arsehole":"a*s*h*l*",
  "aryan":"a*r*a*",
  "ass":"a*s",
  "ass fuck":"a*s*f*c*",
  "ass hole":"a*s*h*l*",
  "assbag":"a*s*a*",
  "assbandit":"a*s*b*n*i*",
  "assbang":"a*s*b*n*",
  "assbanged":"a*s*b*n*e*",
  "assbanger":"a*s*b*n*e*",
  "assbangs":"a*s*a*g*",
  "assbite":"a*s*b*t*",
  "assclown":"a*s*l*w*",
  "asscock":"a*s*c*c*",
  "asscracker":"a*s*r*c*e*",
  "asses":"a*s*e*",
  "assface":"a*s*f*c*",
  "assfaces":"a*s*a*e*",
  "assfuck":"a*s*f*c*",
  "assfucker":"a*s*f*c*e*",
  "ass-fucker":"a*s*f*c*e*",
  "assfukka":"a*s*u*k*",
  "assgoblin":"a*s*g*b*i*",
  "assh0le":"a*s*h*l*",
  "asshat":"a*s*a*",
  "ass-hat":"a*s*-*a*",
  "asshead":"a*s*h*a*",
  "assho1e":"a*s*h*1*",
  "asshole":"a*s*h*l*",
  "assholes":"a*s*o*e*",
  "asshopper":"a*s*h*p*e*",
  "ass-jabber":"a*s*j*b*e*",
  "assjacker":"a*s*j*c*e*",
  "asslick":"a*s*l*c*",
  "asslicker":"a*s*l*c*e*",
  "assmaster":"a*s*m*s*e*",
  "assmonkey":"a*s*m*n*e*",
  "assmucus":"a*s*u*u*",
  "assmunch":"a*s*u*c*",
  "assmuncher":"a*s*u*c*e*",
  "assnigger":"a*s*n*g*e*",
  "asspirate":"a*s*p*r*t*",
  "ass-pirate":"a*s*p*r*t*",
  "assshit":"a*s*s*i*",
  "assshole":"a*s*h*l*",
  "asssucker":"a*s*s*c*e*",
  "asswad":"a*s*a*",
  "asswhole":"a*s*h*l*",
  "asswipe":"a*s*w*p*",
  "asswipes":"a*s*i*e*",
  "auto erotic":"a*u*o*e*o*i*",
  "autoerotic":"a*t*e*o*i*",
  "axwound":"a*x*o*n*",
  "azazel":"a*a*e*",
  "azz":"a*z",
  "b!tch":"b*!*c*",
  "b00bs":"b*0*b*",
  "b17ch":"b*1*c*",
  "b1tch":"b*1*c*",
  "babeland":"b*b*l*n*",
  "baby batter":"b*a*y*b*t*e*",
  "baby juice":"b*b* *u*c*",
  "ball gag":"b*l* *a*",
  "ball gravy":"b*l* *r*v*",
  "ball kicking":"b*l* *i*k*n*",
  "ball licking":"b*l* *i*k*n*",
  "ball sack":"b*a*l*s*c*",
  "ball sucking":"b*l* *u*k*n*",
  "ballbag":"b*a*l*a*",
  "balls":"b*a*l*",
  "ballsack":"b*l*s*c*",
  "bampot":"b*m*o*",
  "bang (one's) box":"b*n* *o*e*s* *ox",
  "bangbros":"b*n*b*o*",
  "bareback":"b*r*b*c*",
  "barely legal":"b*r*l* *e*a*",
  "barenaked":"b*a*e*a*e*",
  "barf":"b*rf",
  "bastard":"b*a*t*r*",
  "bastardo":"b*s*a*d*",
  "bastards":"b*s*a*d*",
  "bastinado":"b*a*t*n*d*",
  "batty boy":"b*a*t* *o*",
  "bawdy":"b*a*d*",
  "bbw":"b*w",
  "bdsm":"b*sm",
  "beaner":"b*a*e*",
  "beaners":"b*e*n*r*",
  "beardedclam":"b*e*r*e*c*a*",
  "beastial":"b*a*t*a*",
  "beastiality":"b*e*s*i*l*t*",
  "beatch":"b*a*c*",
  "beaver":"b*a*e*",
  "beaver cleaver":"b*a*e* *l*a*e*",
  "beaver lips":"b*e*v*r*l*p*",
  "beef curtain":"b*e* *u*t*i*",
  "beef curtains":"b*e*f*c*r*a*n*",
  "beeyotch":"b*e*o*c*",
  "bellend":"b*e*l*n*",
  "bender":"b*n*e*",
  "beotch":"b*o*c*",
  "bescumber":"b*e*c*m*e*",
  "bestial":"b*e*t*a*",
  "bi+ch":"b*i*c*",
  "biatch":"b*a*c*",
  "big black":"b*i* *l*c*",
  "big breasts":"b*i* *r*a*t*",
  "big knockers":"b*g*k*o*k*r*",
  "big tits":"b*g*t*t*",
  "bigtits":"b*i*t*t*",
  "bimbo":"b*i*b*",
  "bimbos":"b*m*o*",
  "bint":"b*nt",
  "birdlock":"b*r*l*c*",
  "bitch tit":"b*i*c* *i*",
  "bitchass":"b*t*h*s*",
  "bitched":"b*i*c*e*",
  "bitcher":"b*i*c*e*",
  "bitchers":"b*t*h*r*",
  "bitches":"b*i*c*e*",
  "bitchin":"b*i*c*i*",
  "bitching":"b*t*h*n*",
  "bitchtits":"b*i*c*t*t*",
  "bitchy":"b*t*h*",
  "black cock":"b*a*k*c*c*",
  "blonde action":"b*l*n*e*a*t*o*",
  "blonde on blonde action":"b*l*n*e*o* *l*nde action",
  "bloodclaat":"b*o*d*l*a*",
  "bloody":"b*o*d*",
  "bloody hell":"b*l*o*y*h*l*",
  "blow job":"b*o* *o*",
  "blow me":"b*l*w*m*",
  "blow mud":"b*o* *u*",
  "blow your load":"b*o* *o*r*l*a*",
  "blowjobs":"b*o*j*b*",
  "blue waffle":"b*l*e*w*f*l*",
  "blumpkin":"b*u*p*i*",
  "bod":"b*d",
  "bodily":"b*d*l*",
  "boink":"b*o*n*",
  "boiolas":"b*o*o*a*",
  "bollock":"b*o*l*c*",
  "bollocks":"b*l*o*k*",
  "bollok":"b*l*o*",
  "bollox":"b*l*o*",
  "bondage":"b*o*d*g*",
  "boned":"b*o*e*",
  "boner":"b*o*e*",
  "boners":"b*n*r*",
  "bong":"b*ng",
  "boob":"b*ob",
  "boobies":"b*o*b*e*",
  "boobs":"b*o*b*",
  "booby":"b*o*b*",
  "booger":"b*o*e*",
  "bookie":"b*o*i*",
  "boong":"b*o*n*",
  "booobs":"b*o*b*",
  "boooobs":"b*o*o*b*",
  "booooobs":"b*o*o*b*",
  "booooooobs":"b*o*o*o*b*",
  "bootee":"b*o*e*",
  "bootie":"b*o*i*",
  "booty":"b*o*t*",
  "booty call":"b*o*y*c*l*",
  "booze":"b*o*z*",
  "boozer":"b*o*e*",
  "boozy":"b*o*z*",
  "bosom":"b*o*o*",
  "bosomy":"b*s*m*",
  "breasts":"b*r*a*t*",
  "Breeder":"B*r*e*e*",
  "brotherfucker":"b*r*t*e*f*c*e*",
  "brown showers":"b*r*w* *h*w*r*",
  "brunette action":"b*r*n*t*e*a*t*on",
  "buceta":"b*c*t*",
  "bugger":"b*g*e*",
  "bukkake":"b*u*k*k*",
  "bull shit":"b*u*l*s*i*",
  "bulldyke":"b*l*d*k*",
  "bullet vibe":"b*u*l*t*v*b*",
  "bullshit":"b*l*s*i*",
  "bullshits":"b*u*l*h*t*",
  "bullshitted":"b*u*l*h*t*e*",
  "bullturds":"b*u*l*u*d*",
  "bum":"b*m",
  "bum boy":"b*u* *o*",
  "bumblefuck":"b*m*l*f*c*",
  "bumclat":"b*u*c*a*",
  "bummer":"b*m*e*",
  "buncombe":"b*n*o*b*",
  "bung":"b*ng",
  "bung hole":"b*u*g*h*l*",
  "bunghole":"b*n*h*l*",
  "bunny fucker":"b*n*y*f*c*e*",
  "bust a load":"b*u*t*a*l*a*",
  "busty":"b*u*t*",
  "butt":"b*tt",
  "butt fuck":"b*u*t*f*c*",
  "butt plug":"b*u*t*p*u*",
  "buttcheeks":"b*t*c*e*k*",
  "buttfuck":"b*t*f*c*",
  "buttfucka":"b*u*t*u*k*",
  "buttfucker":"b*t*f*c*e*",
  "butthole":"b*t*h*l*",
  "buttmuch":"b*t*m*c*",
  "buttmunch":"b*u*t*u*c*",
  "butt-pirate":"b*u*t*p*r*t*",
  "buttplug":"b*t*p*u*",
  "c.0.c.k":"c*.*.*.*",
  "c.o.c.k.":"c*o*c*k*",
  "c.u.n.t":"c*.*.*.*",
  "c0ck":"c*ck",
  "c-0-c-k":"c*-*-*-*",
  "c0cksucker":"c*c*s*c*e*",
  "caca":"c*ca",
  "cacafuego":"c*a*a*u*g*",
  "cahone":"c*h*n*",
  "camel toe":"c*a*e* *o*",
  "cameltoe":"c*m*l*o*",
  "camgirl":"c*a*g*r*",
  "camslut":"c*a*s*u*",
  "camwhore":"c*m*h*r*",
  "carpet muncher":"c*r*e* *u*c*e*",
  "carpetmuncher":"c*a*p*t*u*c*e*",
  "cawk":"c*wk",
  "cervix":"c*r*i*",
  "chesticle":"c*h*s*i*l*",
  "chi-chi man":"c*h*-*h* *a*",
  "chick with a dick":"c*h*c* *i*h*a*dick",
  "child-fucker":"c*i*d*f*c*e*",
  "chinc":"c*h*n*",
  "chincs":"c*i*c*",
  "chink":"c*h*n*",
  "chinky":"c*i*k*",
  "choad":"c*h*a*",
  "choade":"c*o*d*",
  "choc ice":"c*o* *c*",
  "chocolate rosebuds":"c*o*o*a*e*r*s*buds",
  "chode":"c*h*d*",
  "chodes":"c*o*e*",
  "chota bags":"c*o*a*b*g*",
  "cipa":"c*pa",
  "circlejerk":"c*r*l*j*r*",
  "cl1t":"c*1t",
  "cleveland steamer":"c*l*v*l*n* *t*amer",
  "climax":"c*i*a*",
  "clit":"c*it",
  "clit licker":"c*l*t*l*c*e*",
  "clitface":"c*i*f*c*",
  "clitfuck":"c*i*f*c*",
  "clitoris":"c*i*o*i*",
  "clitorus":"c*i*o*u*",
  "clits":"c*l*t*",
  "clitty":"c*i*t*",
  "clitty litter":"c*l*t*y*l*t*e*",
  "clover clamps":"c*l*v*r*c*a*p*",
  "clunge":"c*u*g*",
  "clusterfuck":"c*l*s*e*f*c*",
  "cnut":"c*ut",
  "cocain":"c*c*i*",
  "cocaine":"c*o*a*n*",
  "coccydynia":"c*c*y*y*i*",
  "c-o-c-k":"c*-*-*-*",
  "cock pocket":"c*o*k*p*c*e*",
  "cock snot":"c*o*k*s*o*",
  "cock sucker":"c*o*k*s*c*e*",
  "cockass":"c*o*k*s*",
  "cockbite":"c*c*b*t*",
  "cockblock":"c*o*k*l*c*",
  "cockburger":"c*c*b*r*e*",
  "cockeye":"c*o*k*y*",
  "cockface":"c*c*f*c*",
  "cockfucker":"c*c*f*c*e*",
  "cockhead":"c*c*h*a*",
  "cockholster":"c*o*k*o*s*e*",
  "cockjockey":"c*c*j*c*e*",
  "cockknocker":"c*o*k*n*c*e*",
  "cockknoker":"c*c*k*o*e*",
  "Cocklump":"C*c*l*m*",
  "cockmaster":"c*c*m*s*e*",
  "cockmongler":"c*o*k*o*g*e*",
  "cockmongruel":"c*c*m*n*r*e*",
  "cockmonkey":"c*c*m*n*e*",
  "cockmunch":"c*o*k*u*c*",
  "cockmuncher":"c*o*k*u*c*e*",
  "cocknose":"c*c*n*s*",
  "cocknugget":"c*c*n*g*e*",
  "cocks":"c*o*k*",
  "cockshit":"c*c*s*i*",
  "cocksmith":"c*o*k*m*t*",
  "cocksmoke":"c*o*k*m*k*",
  "cocksmoker":"c*c*s*o*e*",
  "cocksniffer":"c*o*k*n*f*e*",
  "cocksuck":"c*c*s*c*",
  "cocksucked":"c*c*s*c*e*",
  "cocksucker":"c*c*s*c*e*",
  "cock-sucker":"c*o*k*s*c*e*",
  "cocksuckers":"c*o*k*u*k*r*",
  "cocksucking":"c*o*k*u*k*n*",
  "cocksucks":"c*o*k*u*k*",
  "cocksuka":"c*c*s*k*",
  "cocksukka":"c*o*k*u*k*",
  "cockwaffle":"c*c*w*f*l*",
  "coffin dodger":"c*o*f*n*d*d*e*",
  "coital":"c*i*a*",
  "cok":"c*k",
  "cokmuncher":"c*k*u*c*e*",
  "coksucka":"c*k*u*k*",
  "commie":"c*m*i*",
  "condom":"c*n*o*",
  "coochie":"c*o*c*i*",
  "coochy":"c*o*h*",
  "coon":"c*on",
  "coonnass":"c*o*n*s*",
  "coons":"c*o*n*",
  "cooter":"c*o*e*",
  "cop some wood":"c*o* *o*e*w*o*",
  "coprolagnia":"c*o*r*l*g*i*",
  "coprophilia":"c*o*r*p*i*i*",
  "corksucker":"c*r*s*c*e*",
  "cornhole":"c*r*h*l*",
  "corp whore":"c*r* *h*r*",
  "corpulent":"c*o*p*l*n*",
  "cox":"c*x",
  "crabs":"c*r*b*",
  "crack":"c*r*c*",
  "cracker":"c*r*c*e*",
  "crackwhore":"c*a*k*h*r*",
  "crap":"c*ap",
  "crappy":"c*a*p*",
  "creampie":"c*e*m*i*",
  "cretin":"c*e*i*",
  "crikey":"c*i*e*",
  "cripple":"c*r*p*l*",
  "crotte":"c*o*t*",
  "cum":"c*m",
  "cum chugger":"c*u* *h*g*e*",
  "cum dumpster":"c*m*d*m*s*e*",
  "cum freak":"c*u* *r*a*",
  "cum guzzler":"c*u* *u*z*e*",
  "cumbubble":"c*u*b*b*l*",
  "cumdump":"c*u*d*m*",
  "cumdumpster":"c*u*d*m*s*e*",
  "cumguzzler":"c*m*u*z*e*",
  "cumjockey":"c*u*j*c*e*",
  "cummer":"c*m*e*",
  "cummin":"c*m*i*",
  "cumming":"c*u*m*n*",
  "cums":"c*ms",
  "cumshot":"c*u*s*o*",
  "cumshots":"c*m*h*t*",
  "cumslut":"c*u*s*u*",
  "cumstain":"c*m*t*i*",
  "cumtart":"c*u*t*r*",
  "cunilingus":"c*n*l*n*u*",
  "cunillingus":"c*u*i*l*n*u*",
  "cunnie":"c*n*i*",
  "cunnilingus":"c*u*n*l*n*u*",
  "cunny":"c*u*n*",
  "cunt":"c*nt",
  "c-u-n-t":"c*-*-*-*",
  "cunt hair":"c*u*t*h*i*",
  "cuntass":"c*u*t*s*",
  "cuntbag":"c*u*t*a*",
  "cuntface":"c*n*f*c*",
  "cunthole":"c*n*h*l*",
  "cunthunter":"c*n*h*n*e*",
  "cuntlick":"c*n*l*c*",
  "cuntlicker":"c*n*l*c*e*",
  "cuntlicking":"c*u*t*i*k*n*",
  "cuntrag":"c*u*t*a*",
  "cunts":"c*u*t*",
  "cuntsicle":"c*u*t*i*l*",
  "cuntslut":"c*n*s*u*",
  "cunt-struck":"c*u*t*s*r*c*",
  "cus":"c*s",
  "cut rope":"c*t*r*p*",
  "cyalis":"c*a*i*",
  "cyberfuc":"c*b*r*u*",
  "cyberfuck":"c*y*e*f*c*",
  "cyberfucked":"c*y*e*f*c*e*",
  "cyberfucker":"c*y*e*f*c*e*",
  "cyberfuckers":"c*b*r*u*k*r*",
  "cyberfucking":"c*b*r*u*k*n*",
  "d0ng":"d*ng",
  "d0uch3":"d*u*h*",
  "d0uche":"d*u*h*",
  "d1ck":"d*ck",
  "d1ld0":"d*1*d*",
  "d1ldo":"d*1*d*",
  "dago":"d*go",
  "dagos":"d*a*o*",
  "dammit":"d*m*i*",
  "damn":"d*mn",
  "damned":"d*m*e*",
  "damnit":"d*m*i*",
  "darkie":"d*r*i*",
  "darn":"d*rn",
  "date rape":"d*a*e*r*p*",
  "daterape":"d*t*r*p*",
  "dawgie-style":"d*w*i*-*t*l*",
  "deep throat":"d*e*p*t*r*a*",
  "deepthroat":"d*e*t*r*a*",
  "deggo":"d*e*g*",
  "dendrophilia":"d*n*r*p*i*i*",
  "dick":"d*ck",
  "dick head":"d*i*k*h*a*",
  "dick hole":"d*i*k*h*l*",
  "dick shy":"d*c* *h*",
  "dickbag":"d*i*k*a*",
  "dickbeaters":"d*i*k*e*t*r*",
  "dickdipper":"d*c*d*p*e*",
  "dickface":"d*c*f*c*",
  "dickflipper":"d*i*k*l*p*e*",
  "dickfuck":"d*c*f*c*",
  "dickfucker":"d*c*f*c*e*",
  "dickhead":"d*c*h*a*",
  "dickheads":"d*i*k*e*d*",
  "dickhole":"d*c*h*l*",
  "dickish":"d*i*k*s*",
  "dick-ish":"d*c*-*s*",
  "dickjuice":"d*i*k*u*c*",
  "dickmilk":"d*c*m*l*",
  "dickmonger":"d*c*m*n*e*",
  "dickripper":"d*c*r*p*e*",
  "dicks":"d*i*k*",
  "dicksipper":"d*c*s*p*e*",
  "dickslap":"d*c*s*a*",
  "dick-sneeze":"d*i*k*s*e*z*",
  "dicksucker":"d*c*s*c*e*",
  "dicksucking":"d*i*k*u*k*n*",
  "dicktickler":"d*i*k*i*k*e*",
  "dickwad":"d*i*k*a*",
  "dickweasel":"d*c*w*a*e*",
  "dickweed":"d*c*w*e*",
  "dickwhipper":"d*i*k*h*p*e*",
  "dickwod":"d*i*k*o*",
  "dickzipper":"d*c*z*p*e*",
  "diddle":"d*d*l*",
  "dike":"d*ke",
  "dildo":"d*i*d*",
  "dildos":"d*l*o*",
  "diligaf":"d*i*i*a*",
  "dillweed":"d*l*w*e*",
  "dimwit":"d*m*i*",
  "dingle":"d*n*l*",
  "dingleberries":"d*i*g*e*e*r*e*",
  "dingleberry":"d*i*g*e*e*r*",
  "dink":"d*nk",
  "dinks":"d*i*k*",
  "dipship":"d*i*s*i*",
  "dipshit":"d*i*s*i*",
  "dirsa":"d*i*s*",
  "dirty":"d*i*t*",
  "dirty pillows":"d*i*t* *i*l*w*",
  "dirty sanchez":"d*i*t* *a*c*e*",
  "div":"d*v",
  "dlck":"d*ck",
  "dog style":"d*o* *t*l*",
  "dog-fucker":"d*g*f*c*e*",
  "doggie style":"d*g*i* *t*l*",
  "doggiestyle":"d*o*g*e*t*l*",
  "doggie-style":"d*g*i*-*t*l*",
  "doggin":"d*g*i*",
  "dogging":"d*o*g*n*",
  "doggy style":"d*o*g* *t*l*",
  "doggystyle":"d*g*y*t*l*",
  "doggy-style":"d*o*g*-*t*l*",
  "dolcett":"d*o*c*t*",
  "domination":"d*m*n*t*o*",
  "dominatrix":"d*m*n*t*i*",
  "dommes":"d*m*e*",
  "dong":"d*ng",
  "donkey punch":"d*n*e* *u*c*",
  "donkeypunch":"d*o*k*y*u*c*",
  "donkeyribber":"d*n*e*r*b*e*",
  "doochbag":"d*o*h*a*",
  "doofus":"d*o*u*",
  "dookie":"d*o*i*",
  "doosh":"d*o*s*",
  "dopey":"d*o*e*",
  "double dong":"d*o*b*e*d*n*",
  "double penetration":"d*u*l* *e*e*r*tion",
  "Doublelift":"D*u*l*l*f*",
  "douch3":"d*u*h*",
  "douche":"d*u*h*",
  "douchebag":"d*o*c*e*a*",
  "douchebags":"d*u*h*b*g*",
  "douche-fag":"d*u*h*-*a*",
  "douchewaffle":"d*u*h*w*f*l*",
  "douchey":"d*o*c*e*",
  "dp action":"d*p*a*t*o*",
  "drunk":"d*r*n*",
  "dry hump":"d*y*h*m*",
  "duche":"d*u*h*",
  "dumass":"d*m*s*",
  "dumb ass":"d*m* *s*",
  "dumbass":"d*u*b*s*",
  "dumbasses":"d*u*b*s*e*",
  "Dumbcunt":"D*m*c*n*",
  "dumbfuck":"d*m*f*c*",
  "dumbshit":"d*m*s*i*",
  "dummy":"d*u*m*",
  "dumshit":"d*u*s*i*",
  "dvda":"d*da",
  "dyke":"d*ke",
  "dykes":"d*y*e*",
  "eat a dick":"e*t*a*d*c*",
  "eat hair pie":"e*t*h*i* *i*",
  "eat my ass":"e*t*m* *s*",
  "ecchi":"e*c*h*",
  "ejaculate":"e*j*c*l*t*",
  "ejaculated":"e*a*u*a*e*",
  "ejaculates":"e*a*u*a*e*",
  "ejaculating":"e*j*c*l*t*n*",
  "ejaculatings":"e*a*u*a*i*g*",
  "ejaculation":"e*j*c*l*t*o*",
  "ejakulate":"e*j*k*l*t*",
  "erect":"e*r*c*",
  "erection":"e*e*t*o*",
  "erotism":"e*r*t*s*",
  "escort":"e*c*r*",
  "essohbee":"e*s*h*e*",
  "eunuch":"e*n*c*",
  "extacy":"e*t*c*",
  "extasy":"e*t*s*",
  "f u c k":"f* * * *",
  "f u c k e r":"f* * * * * *",
  "f.u.c.k":"f*.*.*.*",
  "f_u_c_k":"f*_*_*_*",
  "f4nny":"f*4*n*",
  "facial":"f*c*a*",
  "fack":"f*ck",
  "fag":"f*g",
  "fagbag":"f*g*a*",
  "fagfucker":"f*a*f*c*e*",
  "fagg":"f*gg",
  "fagged":"f*g*e*",
  "fagging":"f*a*g*n*",
  "faggit":"f*g*i*",
  "faggitt":"f*a*g*t*",
  "faggot":"f*g*o*",
  "faggotcock":"f*g*o*c*c*",
  "faggots":"f*a*g*t*",
  "faggs":"f*a*g*",
  "fagot":"f*a*o*",
  "fagots":"f*g*t*",
  "fags":"f*gs",
  "fagtard":"f*a*t*r*",
  "faig":"f*ig",
  "faigt":"f*a*g*",
  "fanny":"f*a*n*",
  "fannybandit":"f*a*n*b*n*i*",
  "fannyflaps":"f*n*y*l*p*",
  "fannyfucker":"f*a*n*f*c*e*",
  "fanyy":"f*a*y*",
  "fart":"f*rt",
  "fartknocker":"f*a*t*n*c*e*",
  "fatass":"f*t*s*",
  "fcuk":"f*uk",
  "fcuker":"f*u*e*",
  "fcuking":"f*c*k*n*",
  "fecal":"f*e*a*",
  "feck":"f*ck",
  "fecker":"f*c*e*",
  "feist":"f*e*s*",
  "felch":"f*e*c*",
  "felcher":"f*e*c*e*",
  "felching":"f*l*h*n*",
  "fellate":"f*e*l*t*",
  "fellatio":"f*l*a*i*",
  "feltch":"f*l*c*",
  "feltcher":"f*l*c*e*",
  "female squirting":"f*m*l* *q*i*t*ng",
  "femdom":"f*m*o*",
  "fenian":"f*n*a*",
  "fice":"f*ce",
  "figging":"f*i*g*n*",
  "fingerbang":"f*n*e*b*n*",
  "fingerfuck":"f*n*e*f*c*",
  "fingerfucked":"f*n*e*f*c*e*",
  "fingerfucker":"f*n*e*f*c*e*",
  "fingerfuckers":"f*i*g*r*u*k*r*",
  "fingerfucking":"f*i*g*r*u*k*n*",
  "fingerfucks":"f*i*g*r*u*k*",
  "fingering":"f*i*g*r*n*",
  "fist fuck":"f*i*t*f*c*",
  "fisted":"f*s*e*",
  "fistfuck":"f*s*f*c*",
  "fistfucked":"f*s*f*c*e*",
  "fistfucker":"f*s*f*c*e*",
  "fistfuckers":"f*i*t*u*k*r*",
  "fistfucking":"f*i*t*u*k*n*",
  "fistfuckings":"f*s*f*c*i*g*",
  "fistfucks":"f*i*t*u*k*",
  "fisting":"f*i*t*n*",
  "fisty":"f*i*t*",
  "flamer":"f*a*e*",
  "flange":"f*a*g*",
  "flaps":"f*l*p*",
  "fleshflute":"f*e*h*l*t*",
  "flog the log":"f*o* *h* *o*",
  "floozy":"f*o*z*",
  "foad":"f*ad",
  "foah":"f*ah",
  "fondle":"f*n*l*",
  "foobar":"f*o*a*",
  "fook":"f*ok",
  "fooker":"f*o*e*",
  "foot fetish":"f*o*t*f*t*s*",
  "footjob":"f*o*t*o*",
  "foreskin":"f*r*s*i*",
  "freex":"f*r*e*",
  "frenchify":"f*r*n*h*f*",
  "frigg":"f*r*g*",
  "frigga":"f*i*g*",
  "frotting":"f*o*t*n*",
  "fubar":"f*u*a*",
  "fuc":"f*c",
  "f-u-c-k":"f*-*-*-*",
  "fuck buttons":"f*c* *u*t*n*",
  "fuck hole":"f*u*k*h*l*",
  "Fuck off":"F*c* *f*",
  "fuck puppet":"f*u*k*p*p*e*",
  "fuck trophy":"f*u*k*t*o*h*",
  "fuck yo mama":"f*c* *o*m*m*",
  "fucka":"f*u*k*",
  "fuckass":"f*u*k*s*",
  "fuck-ass":"f*c*-*s*",
  "fuckbag":"f*u*k*a*",
  "fuck-bitch":"f*c*-*i*c*",
  "fuckboy":"f*u*k*o*",
  "fuckbrain":"f*u*k*r*i*",
  "fuckbutt":"f*c*b*t*",
  "fuckbutter":"f*c*b*t*e*",
  "fucked":"f*c*e*",
  "fuckedup":"f*c*e*u*",
  "fucker":"f*c*e*",
  "fuckers":"f*u*k*r*",
  "fuckersucker":"f*c*e*s*c*e*",
  "fuckface":"f*c*f*c*",
  "fuckhead":"f*c*h*a*",
  "fuckheads":"f*u*k*e*d*",
  "fuckhole":"f*c*h*l*",
  "fuckin":"f*c*i*",
  "fucking":"f*u*k*n*",
  "fuckings":"f*c*i*g*",
  "fuckingshitmotherfucker":"f*u*k*n*s*i*m*therfucker",
  "fuckme":"f*c*m*",
  "fuckmeat":"f*c*m*a*",
  "fucknugget":"f*c*n*g*e*",
  "fucknut":"f*u*k*u*",
  "fucknutt":"f*c*n*t*",
  "fuckoff":"f*u*k*f*",
  "fucks":"f*u*k*",
  "fuckstick":"f*u*k*t*c*",
  "fucktard":"f*c*t*r*",
  "fuck-tard":"f*u*k*t*r*",
  "fucktards":"f*u*k*a*d*",
  "fucktart":"f*c*t*r*",
  "fucktoy":"f*u*k*o*",
  "fucktwat":"f*c*t*a*",
  "fuckup":"f*c*u*",
  "fuckwad":"f*u*k*a*",
  "fuckwhit":"f*c*w*i*",
  "fuckwit":"f*u*k*i*",
  "fuckwitt":"f*c*w*t*",
  "fudge packer":"f*d*e*p*c*e*",
  "fudgepacker":"f*u*g*p*c*e*",
  "fudge-packer":"f*d*e*p*c*e*",
  "fuk":"f*k",
  "fuker":"f*u*e*",
  "fukker":"f*k*e*",
  "fukkers":"f*u*k*r*",
  "fukkin":"f*k*i*",
  "fuks":"f*ks",
  "fukwhit":"f*u*w*i*",
  "fukwit":"f*k*i*",
  "fuq":"f*q",
  "futanari":"f*t*n*r*",
  "fux":"f*x",
  "fux0r":"f*u*0*",
  "fvck":"f*ck",
  "fxck":"f*ck",
  "gae":"g*e",
  "gai":"g*i",
  "gang bang":"g*a*g*b*n*",
  "gangbang":"g*n*b*n*",
  "gang-bang":"g*a*g*b*n*",
  "gangbanged":"g*n*b*n*e*",
  "gangbangs":"g*a*g*a*g*",
  "ganja":"g*a*j*",
  "gash":"g*sh",
  "gassy ass":"g*a*s* *s*",
  "gay sex":"g*a* *e*",
  "gayass":"g*y*s*",
  "gaybob":"g*y*o*",
  "gaydo":"g*a*d*",
  "gayfuck":"g*a*f*c*",
  "gayfuckist":"g*y*u*k*s*",
  "gaylord":"g*a*l*r*",
  "gays":"g*ys",
  "gaysex":"g*y*e*",
  "gaytard":"g*a*t*r*",
  "gaywad":"g*y*a*",
  "gender bender":"g*e*d*r*b*n*e*",
  "genitals":"g*n*t*l*",
  "gey":"g*y",
  "gfy":"g*y",
  "ghay":"g*ay",
  "ghey":"g*ey",
  "giant cock":"g*a*t*c*c*",
  "ginger":"g*n*e*",
  "gippo":"g*i*p*",
  "girl on":"g*i*l*o*",
  "girl on top":"g*i*l*o* *o*",
  "girls gone wild":"g*i*l* *o*e*w*ld",
  "git":"g*t",
  "glans":"g*l*n*",
  "goatcx":"g*a*c*",
  "goatse":"g*a*s*",
  "god":"g*d",
  "god damn":"g*d*d*m*",
  "godamn":"g*d*m*",
  "godamnit":"g*d*m*i*",
  "goddam":"g*d*a*",
  "god-dam":"g*o*-*a*",
  "goddammit":"g*o*d*m*i*",
  "goddamn":"g*o*d*m*",
  "goddamned":"g*o*d*m*e*",
  "god-damned":"g*d*d*m*e*",
  "goddamnit":"g*o*d*m*i*",
  "godsdamn":"g*d*d*m*",
  "gokkun":"g*k*u*",
  "golden shower":"g*o*d*n*s*o*e*",
  "goldenshower":"g*l*e*s*o*e*",
  "golliwog":"g*l*i*o*",
  "gonad":"g*o*a*",
  "gonads":"g*n*d*",
  "goo girl":"g*o*g*r*",
  "gooch":"g*o*c*",
  "goodpoop":"g*o*p*o*",
  "gook":"g*ok",
  "gooks":"g*o*k*",
  "goregasm":"g*r*g*s*",
  "gringo":"g*i*g*",
  "grope":"g*r*p*",
  "group sex":"g*r*u* *e*",
  "gspot":"g*s*o*",
  "g-spot":"g*s*o*",
  "gtfo":"g*fo",
  "guido":"g*u*d*",
  "guro":"g*ro",
  "h0m0":"h*m0",
  "h0mo":"h*mo",
  "ham flap":"h*m*f*a*",
  "hand job":"h*n* *o*",
  "hard core":"h*a*d*c*r*",
  "hard on":"h*a*d*o*",
  "hardcore":"h*r*c*r*",
  "hardcoresex":"h*a*d*o*e*e*",
  "he11":"h*11",
  "hebe":"h*be",
  "heeb":"h*eb",
  "hell":"h*ll",
  "hemp":"h*mp",
  "hentai":"h*n*a*",
  "heroin":"h*r*i*",
  "herp":"h*rp",
  "herpes":"h*r*e*",
  "herpy":"h*e*p*",
  "heshe":"h*e*h*",
  "he-she":"h*-*h*",
  "hircismus":"h*i*c*s*u*",
  "hitler":"h*t*e*",
  "hiv":"h*v",
  "ho":"h*",
  "hoar":"h*ar",
  "hoare":"h*o*r*",
  "hobag":"h*o*a*",
  "hoe":"h*e",
  "hoer":"h*er",
  "holy shit":"h*o*y*s*i*",
  "hom0":"h*m0",
  "homey":"h*o*e*",
  "homodumbshit":"h*m*d*m*s*i*",
  "homoerotic":"h*m*e*o*i*",
  "homoey":"h*m*e*",
  "honkey":"h*n*e*",
  "honky":"h*o*k*",
  "hooch":"h*o*c*",
  "hookah":"h*o*a*",
  "hooker":"h*o*e*",
  "hoor":"h*or",
  "hootch":"h*o*c*",
  "hooter":"h*o*e*",
  "hooters":"h*o*t*r*",
  "hore":"h*re",
  "horniest":"h*r*i*s*",
  "horny":"h*o*n*",
  "hot carl":"h*t*c*r*",
  "hot chick":"h*o* *h*c*",
  "hotsex":"h*t*e*",
  "how to kill":"h*o* *o*k*l*",
  "how to murdep":"h*o* *o*m*r*e*",
  "how to murder":"h*o* *o*m*r*e*",
  "huge fat":"h*g* *a*",
  "hump":"h*mp",
  "humped":"h*m*e*",
  "humping":"h*u*p*n*",
  "hun":"h*n",
  "hussy":"h*u*s*",
  "hymen":"h*y*e*",
  "iap":"i*p",
  "iberian slap":"i*e*i*n*s*a*",
  "inbred":"i*b*e*",
  "incest":"i*c*s*",
  "injun":"i*n*u*",
  "intercourse":"i*n*e*c*u*s*",
  "jack off":"j*c* *f*",
  "jackass":"j*a*k*s*",
  "jackasses":"j*a*k*s*e*",
  "jackhole":"j*c*h*l*",
  "jackoff":"j*a*k*f*",
  "jack-off":"j*c*-*f*",
  "jaggi":"j*a*g*",
  "jagoff":"j*g*f*",
  "jail bait":"j*a*l*b*i*",
  "jailbait":"j*i*b*i*",
  "jap":"j*p",
  "japs":"j*ps",
  "jelly donut":"j*e*l* *o*u*",
  "jerk":"j*rk",
  "jerk off":"j*r* *f*",
  "jerk0ff":"j*e*k*f*",
  "jerkass":"j*e*k*s*",
  "jerked":"j*r*e*",
  "jerkoff":"j*e*k*f*",
  "jerk-off":"j*r*-*f*",
  "jigaboo":"j*i*a*o*",
  "jiggaboo":"j*g*a*o*",
  "jiggerboo":"j*i*g*r*o*",
  "jism":"j*sm",
  "jiz":"j*z",
  "jizm":"j*zm",
  "jizz":"j*zz",
  "jizzed":"j*z*e*",
  "jock":"j*ck",
  "juggs":"j*u*g*",
  "jungle bunny":"j*n*l* *u*n*",
  "junglebunny":"j*u*g*e*u*n*",
  "junkie":"j*n*i*",
  "junky":"j*u*k*",
  "kawk":"k*wk",
  "kike":"k*ke",
  "kikes":"k*i*e*",
  "kill":"k*ll",
  "kinbaku":"k*i*b*k*",
  "kinkster":"k*n*s*e*",
  "kinky":"k*i*k*",
  "klan":"k*an",
  "knob":"k*ob",
  "knob end":"k*o* *n*",
  "knobbing":"k*o*b*n*",
  "knobead":"k*n*b*a*",
  "knobed":"k*o*e*",
  "knobend":"k*n*b*n*",
  "knobhead":"k*o*h*a*",
  "knobjocky":"k*n*b*o*k*",
  "knobjokey":"k*n*b*o*e*",
  "kock":"k*ck",
  "kondum":"k*n*u*",
  "kondums":"k*o*d*m*",
  "kooch":"k*o*c*",
  "kooches":"k*o*c*e*",
  "kootch":"k*o*c*",
  "kraut":"k*r*u*",
  "kum":"k*m",
  "kummer":"k*m*e*",
  "kumming":"k*u*m*n*",
  "kums":"k*ms",
  "kunilingus":"k*n*l*n*u*",
  "kunja":"k*u*j*",
  "kunt":"k*nt",
  "kwif":"k*if",
  "kyke":"k*ke",
  "l3i+ch":"l*i*c*",
  "l3itch":"l*i*c*",
  "lameass":"l*a*e*s*",
  "lardass":"l*a*d*s*",
  "leather restraint":"l*e*t*e* *e*t*aint",
  "leather straight jacket":"l*e*t*e* *t*a*ght jacket",
  "lech":"l*ch",
  "lemon party":"l*e*o* *a*t*",
  "LEN":"L*N",
  "leper":"l*e*e*",
  "lesbians":"l*s*i*n*",
  "lesbo":"l*e*b*",
  "lesbos":"l*s*o*",
  "lez":"l*z",
  "lezza/lesbo":"l*e*z*/*e*b*",
  "lezzie":"l*z*i*",
  "lmao":"l*ao",
  "lmfao":"l*m*a*",
  "loin":"l*in",
  "loins":"l*o*n*",
  "lolita":"l*l*t*",
  "looney":"l*o*e*",
  "lovemaking":"l*v*m*k*n*",
  "lube":"l*be",
  "lust":"l*st",
  "lusting":"l*u*t*n*",
  "lusty":"l*u*t*",
  "m0f0":"m*f0",
  "m0fo":"m*fo",
  "m45terbate":"m*5*e*b*t*",
  "ma5terb8":"m*5*e*b*",
  "ma5terbate":"m*5*e*b*t*",
  "mafugly":"m*a*u*l*",
  "make me come":"m*k* *e*c*m*",
  "male squirting":"m*l* *q*i*t*n*",
  "mams":"m*ms",
  "masochist":"m*a*o*h*s*",
  "massa":"m*a*s*",
  "masterb8":"m*s*e*b*",
  "masterbat*":"m*s*e*b*t*",
  "masterbat3":"m*s*e*b*t*",
  "masterbate":"m*s*e*b*t*",
  "master-bate":"m*a*t*r*b*t*",
  "masterbating":"m*s*e*b*t*n*",
  "masterbation":"m*s*e*b*t*o*",
  "masterbations":"m*a*t*r*a*i*n*",
  "masturbating":"m*s*u*b*t*n*",
  "masturbation":"m*s*u*b*t*o*",
  "maxi":"m*xi",
  "mcfagget":"m*f*g*e*",
  "menage a trois":"m*n*g* * *r*i*",
  "menses":"m*n*e*",
  "menstruate":"m*n*t*u*t*",
  "menstruation":"m*n*t*u*t*o*",
  "meth":"m*th",
  "m-fucking":"m*-*u*k*n*",
  "mick":"m*ck",
  "microphallus":"m*c*o*h*l*u*",
  "middle finger":"m*i*d*e*f*n*e*",
  "midget":"m*d*e*",
  "milf":"m*lf",
  "minge":"m*i*g*",
  "minger":"m*n*e*",
  "missionary position":"m*i*s*o*a*y*p*sition",
  "mof0":"m*f0",
  "mofo":"m*fo",
  "mo-fo":"m*o*f*",
  "molest":"m*l*s*",
  "mong":"m*ng",
  "moo moo foo foo":"m*o* *o* *o* *oo",
  "moolie":"m*o*i*",
  "moron":"m*o*o*",
  "mothafuck":"m*o*h*f*c*",
  "mothafucka":"m*t*a*u*k*",
  "mothafuckas":"m*o*h*f*c*a*",
  "mothafuckaz":"m*o*h*f*c*a*",
  "mothafucked":"m*o*h*f*c*e*",
  "mothafucker":"m*o*h*f*c*e*",
  "mothafuckers":"m*t*a*u*k*r*",
  "mothafuckin":"m*o*h*f*c*i*",
  "mothafucking":"m*t*a*u*k*n*",
  "mothafuckings":"m*o*h*f*c*i*g*",
  "mothafucks":"m*t*a*u*k*",
  "motherfuck":"m*t*e*f*c*",
  "motherfucka":"m*o*h*r*u*k*",
  "motherfucked":"m*t*e*f*c*e*",
  "motherfucker":"m*t*e*f*c*e*",
  "motherfuckers":"m*o*h*r*u*k*r*",
  "motherfuckin":"m*t*e*f*c*i*",
  "motherfucking":"m*o*h*r*u*k*n*",
  "motherfuckings":"m*t*e*f*c*i*g*",
  "motherfuckka":"m*t*e*f*c*k*",
  "motherfucks":"m*o*h*r*u*k*",
  "mound of venus":"m*u*d*o* *e*u*",
  "mr hands":"m* *a*d*",
  "muff":"m*ff",
  "muff diver":"m*f* *i*e*",
  "muff puff":"m*u*f*p*f*",
  "muffdiver":"m*u*f*i*e*",
  "muffdiving":"m*f*d*v*n*",
  "munging":"m*u*g*n*",
  "munter":"m*n*e*",
  "murder":"m*r*e*",
  "mutha":"m*u*h*",
  "muthafecker":"m*u*h*f*c*e*",
  "muthafuckker":"m*t*a*u*k*e*",
  "muther":"m*t*e*",
  "mutherfucker":"m*t*e*f*c*e*",
  "n1gga":"n*1*g*",
  "n1gger":"n*g*e*",
  "nambla":"n*m*l*",
  "napalm":"n*p*l*",
  "nappy":"n*a*p*",
  "nawashi":"n*a*a*h*",
  "nazi":"n*zi",
  "nazism":"n*z*s*",
  "need the dick":"n*e*d*t*e*d*c*",
  "negro":"n*e*r*",
  "neonazi":"n*e*n*z*",
  "nig nog":"n*i* *o*",
  "nigaboo":"n*i*a*o*",
  "nigg3r":"n*g*3*",
  "nigg4h":"n*g*4*",
  "nigga":"n*i*g*",
  "niggah":"n*g*a*",
  "niggas":"n*g*a*",
  "niggaz":"n*g*a*",
  "nigger":"n*g*e*",
  "niggers":"n*i*g*r*",
  "niggle":"n*g*l*",
  "niglet":"n*g*e*",
  "nig-nog":"n*i*-*o*",
  "nimphomania":"n*i*p*o*a*i*",
  "nimrod":"n*m*o*",
  "ninny":"n*i*n*",
  "ninnyhammer":"n*i*n*h*m*e*",
  "nipple":"n*p*l*",
  "nipples":"n*i*p*e*",
  "nob":"n*b",
  "nob jokey":"n*o* *o*e*",
  "nobhead":"n*o*h*a*",
  "nobjocky":"n*b*o*k*",
  "nobjokey":"n*b*o*e*",
  "nonce":"n*o*c*",
  "nsfw images":"n*s*w*i*a*e*",
  "nudity":"n*d*t*",
  "numbnuts":"n*m*n*t*",
  "nut butter":"n*t*b*t*e*",
  "nut sack":"n*t*s*c*",
  "nutsack":"n*u*s*c*",
  "nutter":"n*t*e*",
  "nympho":"n*m*h*",
  "nymphomania":"n*y*p*o*a*i*",
  "octopussy":"o*c*o*u*s*",
  "old bag":"o*l* *a*",
  "omg":"o*g",
  "omorashi":"o*o*a*h*",
  "one cup two girls":"o*n* *u* *w* *irls",
  "one guy one jar":"o*n* *u* *n* *ar",
  "opiate":"o*i*t*",
  "opium":"o*p*u*",
  "orally":"o*a*l*",
  "organ":"o*r*a*",
  "orgasim":"o*r*a*i*",
  "orgasims":"o*g*s*m*",
  "orgasmic":"o*g*s*i*",
  "orgasms":"o*r*a*m*",
  "orgies":"o*g*e*",
  "orgy":"o*gy",
  "ovary":"o*v*r*",
  "ovum":"o*um",
  "ovums":"o*v*m*",
  "p.u.s.s.y.":"p*u*s*s*y*",
  "p0rn":"p*rn",
  "paedophile":"p*e*o*h*l*",
  "paki":"p*ki",
  "panooch":"p*a*o*c*",
  "pansy":"p*a*s*",
  "pantie":"p*n*i*",
  "panties":"p*a*t*e*",
  "panty":"p*a*t*",
  "pawn":"p*wn",
  "pcp":"p*p",
  "pecker":"p*c*e*",
  "peckerhead":"p*c*e*h*a*",
  "pedo":"p*do",
  "pedobear":"p*d*b*a*",
  "pedophile":"p*e*o*h*l*",
  "pedophilia":"p*d*p*i*i*",
  "pedophiliac":"p*e*o*h*l*a*",
  "pee":"p*e",
  "peepee":"p*e*e*",
  "pegging":"p*e*g*n*",
  "penetrate":"p*e*e*r*t*",
  "penetration":"p*e*e*r*t*o*",
  "penial":"p*n*a*",
  "penile":"p*n*l*",
  "penisbanger":"p*e*i*b*n*e*",
  "penisfucker":"p*e*i*f*c*e*",
  "penispuffer":"p*e*i*p*f*e*",
  "perversion":"p*r*e*s*o*",
  "phallic":"p*h*l*i*",
  "phone sex":"p*h*n* *e*",
  "phonesex":"p*o*e*e*",
  "phuck":"p*h*c*",
  "phuk":"p*uk",
  "phuked":"p*u*e*",
  "phuking":"p*h*k*n*",
  "phukked":"p*h*k*e*",
  "phukking":"p*u*k*n*",
  "phuks":"p*h*k*",
  "phuq":"p*uq",
  "piece of shit":"p*i*c* *f*s*i*",
  "pigfucker":"p*i*f*c*e*",
  "pikey":"p*i*e*",
  "pillowbiter":"p*i*l*w*i*e*",
  "pimp":"p*mp",
  "pimpis":"p*m*i*",
  "pinko":"p*i*k*",
  "piss":"p*ss",
  "piss off":"p*s* *f*",
  "piss pig":"p*s* *i*",
  "pissed":"p*s*e*",
  "pissed off":"p*s*e* *f*",
  "pisser":"p*s*e*",
  "pissers":"p*i*s*r*",
  "pisses":"p*s*e*",
  "pissflaps":"p*i*s*l*p*",
  "pissin":"p*s*i*",
  "pissing":"p*i*s*n*",
  "pissoff":"p*i*s*f*",
  "piss-off":"p*s*-*f*",
  "pisspig":"p*i*s*i*",
  "pleasure chest":"p*e*s*r* *h*s*",
  "pms":"p*s",
  "polack":"p*l*c*",
  "pole smoker":"p*o*e*s*o*e*",
  "polesmoker":"p*l*s*o*e*",
  "pollock":"p*o*l*c*",
  "ponyplay":"p*n*p*a*",
  "poof":"p*of",
  "poon":"p*on",
  "poonani":"p*o*n*n*",
  "poonany":"p*o*n*n*",
  "poontang":"p*o*t*n*",
  "poop":"p*op",
  "poop chute":"p*o* *h*t*",
  "poopchute":"p*o*p*h*t*",
  "Poopuncher":"P*o*u*c*e*",
  "porch monkey":"p*r*h*m*n*e*",
  "porchmonkey":"p*o*c*m*n*e*",
  "pornography":"p*o*n*g*a*h*",
  "pornos":"p*r*o*",
  "pot":"p*t",
  "potty":"p*o*t*",
  "prick":"p*r*c*",
  "pricks":"p*i*k*",
  "prickteaser":"p*r*c*t*a*e*",
  "prig":"p*ig",
  "prince albert piercing":"p*i*c* *l*e*t*piercing",
  "prod":"p*od",
  "pron":"p*on",
  "prostitute":"p*o*t*t*t*",
  "prude":"p*r*d*",
  "psycho":"p*y*h*",
  "pthc":"p*hc",
  "pube":"p*be",
  "pubes":"p*u*e*",
  "pubic":"p*u*i*",
  "pubis":"p*u*i*",
  "punani":"p*n*n*",
  "punanny":"p*u*a*n*",
  "punany":"p*n*n*",
  "punkass":"p*u*k*s*",
  "punky":"p*u*k*",
  "punta":"p*u*t*",
  "puss":"p*ss",
  "pusse":"p*u*s*",
  "pussi":"p*u*s*",
  "pussies":"p*u*s*e*",
  "pussy fart":"p*s*y*f*r*",
  "pussy palace":"p*s*y*p*l*c*",
  "pussylicking":"p*s*y*i*k*n*",
  "pussypounder":"p*s*y*o*n*e*",
  "pussys":"p*s*y*",
  "pust":"p*st",
  "puto":"p*to",
  "queaf":"q*u*a*",
  "queef":"q*u*e*",
  "queer":"q*u*e*",
  "queerbait":"q*u*e*b*i*",
  "queerhole":"q*u*e*h*l*",
  "queero":"q*e*r*",
  "queers":"q*e*r*",
  "quicky":"q*i*k*",
  "quim":"q*im",
  "racy":"r*cy",
  "raghead":"r*a*h*a*",
  "raging boner":"r*g*n* *o*e*",
  "raped":"r*a*e*",
  "raper":"r*a*e*",
  "rapey":"r*a*e*",
  "rapist":"r*p*s*",
  "raunch":"r*u*c*",
  "rectal":"r*c*a*",
  "rectum":"r*c*u*",
  "rectus":"r*c*u*",
  "reefer":"r*e*e*",
  "reetard":"r*e*t*r*",
  "reich":"r*e*c*",
  "renob":"r*e*o*",
  "retard":"r*t*r*",
  "retarded":"r*t*r*e*",
  "reverse cowgirl":"r*e*e*s* *o*g*rl",
  "revue":"r*e*u*",
  "rimjaw":"r*m*a*",
  "rimjob":"r*m*o*",
  "rimming":"r*i*m*n*",
  "ritard":"r*t*r*",
  "rosy palm":"r*o*y*p*l*",
  "rosy palm and her 5 sisters":"r*o*y*p*l* *n* her 5 sisters",
  "rtard":"r*t*r*",
  "r-tard":"r*t*r*",
  "rubbish":"r*u*b*s*",
  "rum":"r*m",
  "rump":"r*mp",
  "rumprammer":"r*m*r*m*e*",
  "ruski":"r*u*k*",
  "rusty trombone":"r*s*y*t*o*b*n*",
  "s hit":"s* *i*",
  "s&m":"s*m",
  "s.h.i.t.":"s*h*i*t*",
  "s.o.b.":"s*o*b*",
  "s_h_i_t":"s*_*_*_*",
  "s0b":"s*b",
  "sadism":"s*d*s*",
  "sadist":"s*d*s*",
  "sambo":"s*a*b*",
  "sand nigger":"s*a*d*n*g*e*",
  "sandbar":"s*a*d*a*",
  "Sandler":"S*a*d*e*",
  "sandnigger":"s*n*n*g*e*",
  "sanger":"s*n*e*",
  "santorum":"s*n*o*u*",
  "sausage queen":"s*a*s*g* *u*e*",
  "scag":"s*ag",
  "scantily":"s*a*t*l*",
  "scat":"s*at",
  "schizo":"s*h*z*",
  "schlong":"s*c*l*n*",
  "scissoring":"s*i*s*r*n*",
  "screw":"s*c*e*",
  "screwed":"s*c*e*e*",
  "screwing":"s*r*w*n*",
  "scroat":"s*r*a*",
  "scrog":"s*c*o*",
  "scrot":"s*c*o*",
  "scrote":"s*r*t*",
  "scrotum":"s*c*o*u*",
  "scrud":"s*c*u*",
  "scum":"s*um",
  "seaman":"s*a*a*",
  "seamen":"s*a*e*",
  "seduce":"s*d*c*",
  "semen":"s*e*e*",
  "sexo":"s*xo",
  "sexy":"s*xy",
  "sh!+":"s*!+",
  "sh!t":"s*!t",
  "sh1t":"s*1t",
  "s-h-1-t":"s*-*-*-*",
  "shag":"s*ag",
  "shagger":"s*h*g*e*",
  "shaggin":"s*h*g*i*",
  "shagging":"s*a*g*n*",
  "shamedame":"s*h*m*d*m*",
  "shaved beaver":"s*h*v*d*b*a*e*",
  "shaved pussy":"s*a*e* *u*s*",
  "shemale":"s*h*m*l*",
  "shi+":"s*i+",
  "shibari":"s*h*b*r*",
  "shirt lifter":"s*i*t*l*f*e*",
  "s-h-i-t":"s*-*-*-*",
  "shit ass":"s*i* *s*",
  "shit fucker":"s*h*t*f*c*e*",
  "shitass":"s*h*t*s*",
  "shitbag":"s*h*t*a*",
  "shitbagger":"s*i*b*g*e*",
  "shitblimp":"s*h*t*l*m*",
  "shitbrains":"s*i*b*a*n*",
  "shitbreath":"s*i*b*e*t*",
  "shitcanned":"s*i*c*n*e*",
  "shitcunt":"s*i*c*n*",
  "shitdick":"s*i*d*c*",
  "shite":"s*h*t*",
  "shiteater":"s*h*t*a*e*",
  "shited":"s*i*e*",
  "shitey":"s*i*e*",
  "shitface":"s*i*f*c*",
  "shitfaced":"s*h*t*a*e*",
  "shitfuck":"s*i*f*c*",
  "shitfull":"s*i*f*l*",
  "shithead":"s*i*h*a*",
  "shitheads":"s*h*t*e*d*",
  "shithole":"s*i*h*l*",
  "shithouse":"s*h*t*o*s*",
  "shiting":"s*h*t*n*",
  "shitings":"s*i*i*g*",
  "shits":"s*h*t*",
  "shitspitter":"s*h*t*p*t*e*",
  "shitstain":"s*h*t*t*i*",
  "shitt":"s*h*t*",
  "shitted":"s*h*t*e*",
  "shitter":"s*h*t*e*",
  "shitters":"s*i*t*r*",
  "shittier":"s*i*t*e*",
  "shittiest":"s*h*t*i*s*",
  "shitting":"s*i*t*n*",
  "shittings":"s*h*t*i*g*",
  "shitty":"s*i*t*",
  "shiz":"s*iz",
  "shiznit":"s*h*z*i*",
  "shota":"s*h*t*",
  "shrimping":"s*h*i*p*n*",
  "sissy":"s*i*s*",
  "skag":"s*ag",
  "skank":"s*k*n*",
  "skeet":"s*k*e*",
  "skullfuck":"s*k*l*f*c*",
  "slag":"s*ag",
  "slanteye":"s*a*t*y*",
  "slave":"s*l*v*",
  "sleaze":"s*e*z*",
  "sleazy":"s*e*z*",
  "slope":"s*l*p*",
  "slut":"s*ut",
  "slut bucket":"s*l*t*b*c*e*",
  "slutbag":"s*l*t*a*",
  "slutdumper":"s*u*d*m*e*",
  "slutkiss":"s*u*k*s*",
  "sluts":"s*l*t*",
  "smartass":"s*a*t*s*",
  "smartasses":"s*a*t*s*e*",
  "smeg":"s*eg",
  "smegma":"s*e*m*",
  "smut":"s*ut",
  "smutty":"s*u*t*",
  "snatch":"s*a*c*",
  "sniper":"s*i*e*",
  "snowballing":"s*n*w*a*l*n*",
  "snuff":"s*n*f*",
  "s-o-b":"s*-*-*",
  "sod off":"s*o* *f*",
  "sodom":"s*o*o*",
  "sodomize":"s*d*m*z*",
  "sodomy":"s*d*m*",
  "son of a bitch":"s*n*o* * *i*c*",
  "son of a motherless goat":"s*n*o* * *o*h*rless goat",
  "son of a whore":"s*n*o* * *h*r*",
  "son-of-a-bitch":"s*n*o*-*-*i*c*",
  "souse":"s*o*s*",
  "soused":"s*u*e*",
  "spac":"s*ac",
  "spade":"s*p*d*",
  "sperm":"s*p*r*",
  "spic":"s*ic",
  "spick":"s*p*c*",
  "spik":"s*ik",
  "spiks":"s*p*k*",
  "splooge":"s*p*o*g*",
  "splooge moose":"s*p*o*g* *o*s*",
  "spooge":"s*o*g*",
  "spook":"s*p*o*",
  "spread legs":"s*p*e*d*l*g*",
  "spunk":"s*p*n*",
  "stfu":"s*fu",
  "stiffy":"s*i*f*",
  "stoned":"s*o*e*",
  "strap on":"s*r*p*o*",
  "strapon":"s*t*a*o*",
  "strappado":"s*t*a*p*d*",
  "strip":"s*t*i*",
  "strip club":"s*r*p*c*u*",
  "stroke":"s*r*k*",
  "stupid":"s*u*i*",
  "style doggy":"s*t*l* *o*g*",
  "suck":"s*ck",
  "suckass":"s*u*k*s*",
  "sucked":"s*c*e*",
  "sucking":"s*u*k*n*",
  "sucks":"s*u*k*",
  "suicide girls":"s*u*c*d* *i*l*",
  "sultry women":"s*l*r* *o*e*",
  "sumofabiatch":"s*m*f*b*a*c*",
  "swastika":"s*a*t*k*",
  "swinger":"s*w*n*e*",
  "t1t":"t*t",
  "t1tt1e5":"t*1*t*e*",
  "t1tties":"t*1*t*e*",
  "taff":"t*ff",
  "taig":"t*ig",
  "tainted love":"t*i*t*d*l*v*",
  "taking the piss":"t*a*i*g*t*e*p*ss",
  "tampon":"t*m*o*",
  "tard":"t*rd",
  "tart":"t*rt",
  "taste my":"t*s*e*m*",
  "tawdry":"t*w*r*",
  "tea bagging":"t*e* *a*g*n*",
  "teabagging":"t*a*a*g*n*",
  "teat":"t*at",
  "teets":"t*e*t*",
  "teez":"t*ez",
  "teste":"t*e*t*",
  "testee":"t*s*e*",
  "testes":"t*s*e*",
  "testical":"t*s*i*a*",
  "testicle":"t*s*i*l*",
  "threesome":"t*h*e*s*m*",
  "throating":"t*h*o*t*n*",
  "thrust":"t*r*s*",
  "thug":"t*ug",
  "thundercunt":"t*h*n*e*c*n*",
  "tied up":"t*i*d*u*",
  "tight white":"t*i*h* *h*t*",
  "tinkle":"t*n*l*",
  "tit":"t*t",
  "tit wank":"t*t*w*n*",
  "titfuck":"t*i*f*c*",
  "titi":"t*ti",
  "tities":"t*t*e*",
  "tits":"t*ts",
  "titt":"t*tt",
  "tittie5":"t*i*t*e*",
  "tittiefucker":"t*t*i*f*c*e*",
  "titties":"t*i*t*e*",
  "titty":"t*i*t*",
  "tittyfuck":"t*i*t*f*c*",
  "tittyfucker":"t*i*t*f*c*e*",
  "tittywank":"t*i*t*w*n*",
  "titwank":"t*i*w*n*",
  "toke":"t*ke",
  "tongue in a":"t*o*g*e*i* *",
  "toots":"t*o*t*",
  "tosser":"t*s*e*",
  "towelhead":"t*o*e*h*a*",
  "tramp":"t*r*m*",
  "tranny":"t*a*n*",
  "transsexual":"t*r*n*s*x*a*",
  "trashy":"t*a*h*",
  "tribadism":"t*r*b*d*s*",
  "trumped":"t*r*m*e*",
  "tub girl":"t*b*g*r*",
  "tubgirl":"t*u*g*r*",
  "turd":"t*rd",
  "tush":"t*sh",
  "tushy":"t*u*h*",
  "tw4t":"t*4t",
  "twat":"t*at",
  "twathead":"t*a*h*a*",
  "twatlips":"t*a*l*p*",
  "twats":"t*w*t*",
  "twatty":"t*a*t*",
  "twatwaffle":"t*a*w*f*l*",
  "twink":"t*w*n*",
  "twinkie":"t*w*n*i*",
  "two fingers":"t*w* *i*g*r*",
  "two fingers with tongue":"t*w* *i*g*r* *ith tongue",
  "two girls one cup":"t*w* *i*l* *n* cup",
  "twunt":"t*w*n*",
  "twunter":"t*w*n*e*",
  "ugly":"u*ly",
  "unclefucker":"u*n*l*f*c*e*",
  "undies":"u*d*e*",
  "undressing":"u*d*e*s*n*",
  "unwed":"u*n*e*",
  "upskirt":"u*p*k*r*",
  "urethra play":"u*e*h*a*p*a*",
  "urinal":"u*i*a*",
  "urine":"u*r*n*",
  "urophilia":"u*r*p*i*i*",
  "uterus":"u*e*u*",
  "uzi":"u*i",
  "v14gra":"v*4*r*",
  "v1gra":"v*1*r*",
  "vag":"v*g",
  "vajayjay":"v*j*y*a*",
  "va-j-j":"v*-*-*",
  "valium":"v*l*u*",
  "venus mound":"v*e*u* *o*n*",
  "veqtable":"v*q*a*l*",
  "viagra":"v*a*r*",
  "vibrator":"v*b*a*o*",
  "violet wand":"v*i*l*t*w*n*",
  "virgin":"v*r*i*",
  "vixen":"v*i*e*",
  "vjayjay":"v*j*y*a*",
  "vomit":"v*o*i*",
  "vorarephilia":"v*r*r*p*i*i*",
  "voyeur":"v*y*u*",
  "vulgar":"v*l*a*",
  "w00se":"w*0*s*",
  "wad":"w*d",
  "wang":"w*ng",
  "wank":"w*nk",
  "wanker":"w*n*e*",
  "wankjob":"w*a*k*o*",
  "wanky":"w*a*k*",
  "wazoo":"w*a*o*",
  "wedgie":"w*d*i*",
  "weed":"w*ed",
  "weenie":"w*e*i*",
  "weewee":"w*e*e*",
  "weiner":"w*i*e*",
  "weirdo":"w*i*d*",
  "wench":"w*e*c*",
  "wet dream":"w*e* *r*a*",
  "wetback":"w*e*b*c*",
  "wh0re":"w*h*r*",
  "wh0reface":"w*h*r*f*c*",
  "white power":"w*h*t* *o*e*",
  "whiz":"w*iz",
  "whoar":"w*h*a*",
  "whoralicious":"w*o*a*i*i*u*",
  "whore":"w*h*r*",
  "whorealicious":"w*h*r*a*i*i*u*",
  "whorebag":"w*o*e*a*",
  "whored":"w*o*e*",
  "whoreface":"w*h*r*f*c*",
  "whorehopper":"w*h*r*h*p*e*",
  "whorehouse":"w*o*e*o*s*",
  "whores":"w*o*e*",
  "whoring":"w*h*r*n*",
  "wigger":"w*g*e*",
  "willies":"w*i*l*e*",
  "willy":"w*i*l*",
  "window licker":"w*i*d*w*l*c*e*",
  "wiseass":"w*i*e*s*",
  "wiseasses":"w*i*e*s*e*",
  "wog":"w*g",
  "womb":"w*mb",
  "wop":"w*p",
  "wrapping men":"w*a*p*n* *e*",
  "wrinkled starfish":"w*r*n*l*d*s*a*fish",
  "wtf":"w*f",
  "xrated":"x*a*e*",
  "x-rated":"x*-*a*e*",
  "xx":"x*",
  "yaoi":"y*oi",
  "yeasty":"y*a*t*",
  "yellow showers":"y*l*o* *h*w*r*",
  "yid":"y*d",
  "yiffy":"y*i*f*",
  "yobbo":"y*o*b*",
  "zibbi":"z*i*b*",
  "zoophilia":"z*o*p*i*i*",
  "zubb":"z*bb"
}